// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-VbWs7kDH2jheaPcvR0SN633lNcPfgzY',
    appId: '1:492923037533:web:e554c257d8db45664eaab4',
    messagingSenderId: '492923037533',
    projectId: 'chat-ae358',
    authDomain: 'chat-ae358.firebaseapp.com',
    storageBucket: 'chat-ae358.appspot.com',
    measurementId: 'G-HWPCM7TJ7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeDa7ta2iQgCK0H3qvLMKqSXhs9KxBo2k',
    appId: '1:492923037533:android:50c90d5d91899d0d4eaab4',
    messagingSenderId: '492923037533',
    projectId: 'chat-ae358',
    storageBucket: 'chat-ae358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNRGWQ-4guoUzrfgA7SH3jp6ksX62GbMk',
    appId: '1:492923037533:ios:7482d587a71537964eaab4',
    messagingSenderId: '492923037533',
    projectId: 'chat-ae358',
    storageBucket: 'chat-ae358.appspot.com',
    iosClientId: '492923037533-9cekcmbahgljd28tsh7klb3hkqrdaqqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNRGWQ-4guoUzrfgA7SH3jp6ksX62GbMk',
    appId: '1:492923037533:ios:7482d587a71537964eaab4',
    messagingSenderId: '492923037533',
    projectId: 'chat-ae358',
    storageBucket: 'chat-ae358.appspot.com',
    iosClientId: '492923037533-9cekcmbahgljd28tsh7klb3hkqrdaqqu.apps.googleusercontent.com',
    iosBundleId: 'com.example.signupLogin',
  );
}
